require File.expand_path(File.join(File.dirname(__FILE__), '..', 'spec_helper'))

describe TokenRequestsController do
  include Devise::TestHelpers

  describe 'routing' do
    describe '/tokens/:token_id/token_requests' do
      it 'maps POST to the create action' do
        expect({:post => '/tokens/1/token_requests'}).to \
          route_to(:controller => 'token_requests', :action => 'create',
                   :token_id => '1')
      end
    
      it 'is generated by token_requests_path' do
        expect(token_requests_path(1)).to eq('/tokens/1/token_requests')
      end
    end

    describe '/tokens/:token_id/token_requests/:id/move' do
      it 'maps PUT to the move action' do
        expect({:put => '/tokens/1/token_requests/2/move'}).to \
          route_to(:controller => 'token_requests', :action => 'move',
                   :token_id => '1', :id => '2')
      end
      
      it 'is generated by move_token_request_path' do
        expect(move_token_request_path(1, 2)).to eq('/tokens/1/token_requests/2/move')
      end
    end
  end

  shared_examples_for 'it has an index at another controller' do
    it 'and redirect to the token page' do
      get :index, :token_id => '1'
      expect(response).to redirect_to(token_path('1'))
    end
  end

  context '(with anonymous user)' do
    it_should_behave_like 'it has an index at another controller'

    describe '#create' do
      it 'requires an authenticated user' do
        post :create, :token_id => '1'
        expect(response).to redirect_to(new_user_session_path)
      end
    end

    describe '#destroy' do
      it 'requires an authenticated user' do
        delete :destroy, :token_id => '1', :id => '2'
        expect(response).to redirect_to(new_user_session_path)
      end
    end
  end

  context '(with authenticated user)' do
    before(:each) do
      @user = mock_model('User')
      request.env['warden'] = double('Warden', :authenticate => @user, :authenticate! => @user)
    end

    it_should_behave_like 'it has an index at another controller'

    describe '#create' do
      context 'with invalid data' do
        before(:each) do
          allow(Token).to receive(:find_by_slug!)
          @token_request = mock_model('TokenRequest').as_new_record
          exception = ActiveRecord::RecordInvalid.new(@token_request)
          allow(TokenRequest).to receive(:create!).and_raise(exception)
        end

        it 'renders the tokens/show template' do
          post :create, :token_id => '1'
          expect(response).to render_template('tokens/show')
        end

        it 'assigns the specified token to the template' do
          expect(Token).to receive(:find_by_slug!).with('1').and_return(:the_token)
          post :create, :token_id => '1'
          expect(assigns(:token)).to eq(:the_token)
        end

        it 'assigns the invalid token request to the template' do
          post :create, :token_id => '1'
          expect(assigns(:new_token_request)).to be === @token_request
        end
      end

      context 'with valid data' do
        it 'should create a new TokenRequest associated with the specified token and current user' do
          expect(Token).to receive(:find_by_slug!).with('1').and_return(:the_token)
          expect(TokenRequest).to receive(:create!) \
            .with("purpose" => 'Foo', "urgent" => '1', "token" => :the_token,
                  "user" => @user)
          post :create, :token_id => '1',
            :token_request => {:purpose => 'Foo', :urgent => '1'}
        end

        it 'should redirect to the token page' do
          allow(Token).to receive(:find_by_slug!)
          allow(TokenRequest).to receive(:create!)
          post :create, :token_id => '1'
          expect(response).to redirect_to token_path('1')
        end
      end
    end

    describe '#destroy' do
      it 'destroys the specified TokenRequest' do
        expect(TokenRequest).to receive(:destroy).with('1')
        delete :destroy, :token_id => 'foo', :id => '1'
      end

      it 'redirects to the token page' do
        allow(TokenRequest).to receive(:destroy)
        delete :destroy, :token_id => 'foo', :id => '1'
        expect(response).to redirect_to(token_path('foo'))
      end
    end
    
    describe '#move' do
      let(:token_request) { double('TokenRequest', :move => nil) }

      before(:each) do
        allow(TokenRequest).to receive_messages(:find => token_request)
      end
      
      it 'redirects to the token page' do
        put :move, :token_id => 'foo', :id => '1'
        expect(response).to redirect_to(token_path('foo'))
      end
      
      it 'tells the token which way to move' do
        expect(token_request).to receive(:move).with('movement_direction')
        put :move, :token_id => '1', :id => '2', :where => 'movement_direction'
      end
    end
  end
end
